### PR TITLE
Fix: Cross-Site Request Forgery (CSRF)

### PR DESCRIPTION
**Pull request by anandtiwarics**
Hi, 

Fixed the CSRF Vulnerability by using Flask-WTF lib. Most of the GET requests converted into POST requests.

For more details, please read Flask-WTF documentation.

[https://flask-wtf.readthedocs.io/en/stable/](https://flask-wtf.readthedocs.io/en/stable/)

PS: Clear your browser if you previously ran an older version of ExtAnalysis. CSRF token will be generated.

Thanks,
Anand

### CODE REVIEW

**Review by adam-nygate — CHANGES_REQUESTED** [review]
Hi!

Are you able to provide more details about your fix and why all of your changes are necessary? I.e:
- Why is it necessary to require requests to be POST instead of GET? This substantially changes the applications logic, and so is it outside the remit of the bounty (unless it is absolutely required to alleviate this security issue
- There are surely security issues associated with the hardcoding (and open source nature) of the `secret_key` used by CSRFProtect. Surely there is a better way to implement this.

**Comment by anandtiwarics** [comment]
Hi,

> Why is it necessary to require requests to be POST instead of GET? This substantially changes the applications logic, and so is it outside the remit of the bounty (unless it is absolutely required to alleviate this security issue

GET requests will not be protected with the anti-CSRF token and POST requests are safer than GET requests if request performs some action or submit a form. In this case, we are deleting or uploading the file.

The POST request will not change any application logic. This is the only way and absolutely required to protect the application from CSRF attack. 

> There are surely security issues associated with the hardcoding (and open-source nature) of the secret_key used by CSRFProtect. Surely there is a better way to implement this.

Yes. It is not a secure way to hardcoding the secret keys. 

- Modified the code and sent PR.

Thanks,
Anand

**Review by toufik-airane — APPROVED** [review]
Thank you.

**Review by adam-nygate — APPROVED** [review]
LGTM 👍

**Comment by huntr-helper** [comment]
Congratulations @anandtiwarics - your fix has been selected! :tada:<br><br>Thanks for being part of the community & helping secure the world\'s open source code.<br>If you have any questions, please respond in the comments section. Your bounty is on its way - keep hunting!

**Pull request merged**
